export const blockchainConstants = [
  "/blockchains/pimg1.svg",
  "/blockchains/pimg2.svg",
  "/blockchains/pimg3.svg",
  "/blockchains/pimg4.svg",
  "/blockchains/pimg5.svg",
  "/blockchains/pimg6.svg",
  "/blockchains/pimg7.svg",
  "/blockchains/pimg8.svg",
];

export const dapps = [
  "/dapps/adlunam.svg",
  "/dapps/dos.svg",
  "/dapps/foodverse.svg",
  "/dapps/img1.svg",
  "/dapps/img2.svg",
  "/dapps/img3.svg",
  "/dapps/img4.svg",
  "/dapps/img5.svg",
  "/dapps/metaluxe.svg",
  "/dapps/ouch.svg",
  "/dapps/unite.svg",
  "/dapps/Welln3ss.svg",
  "/dapps/yogaverse.svg",
];

export const partners = [
  "/partners/aws.svg",
  "/partners/bitmart.svg",
  "/partners/dao.svg",
  "/partners/floor.svg",
  "/partners/img11.svg",
  "/partners/img22.svg",
  "/partners/img33.svg",
  "/partners/img44.svg",
  "/partners/img55.svg",
  "/partners/img66.svg",
  "/partners/img77.svg",
  "/partners/img88.svg",
  "/partners/img99.svg",
  "/partners/ipfs.svg",
  "/partners/jpegd.svg",
  "/partners/nftxy.svg",
  "/partners/reservair.svg",
  "/partners/sandbox.svg",
  "/partners/sudoswap.svg",
  "/partners/trustwallet.svg",
];
